spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/result
    username: root
    password: Ameame123
logging:
  level:
    com.lingoland.springbootmybatis.mapper: debug

swagger:
  enabled: true
server:
  port: 8081